import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import HeroImage from "../public/assets/hero.png";

export default function Home() {
	return (
		<>
			<Head>
				<title>Front-End Developer | Sheena</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
					integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
					crossOrigin="anonymous"
					referrerPolicy="no-referrer"
				/>
			</Head>

			<div class="lg:grid lg:grid-cols-10">
				<aside
					class="self-start lg:sticky lg:h-screen  top-0 col-span-3 flex p-14 flex-col justify-center "
					id="sidebar">
					<Hero />
				</aside>

				<main class="lg:col-span-7 text-white bg-slate-800 drop-shadow-2xl ">
					<div className="   ">
						<Image
							src={HeroImage}
							alt="a picture of me, smiling at you"
							className="lg:h-screen sm:h-[50rem] h-96 grayscale  hover:grayscale-0  transition-all duration-700  object-cover object-top "
						/>
					</div>
					<div className="  p-14 ">
						<Projects id="projects" />
					</div>
					<div className=" flex items-center flex-col p-14 ">
						<About />
					</div>
					<Footer />
				</main>
			</div>
		</>
	);
}
